version: "3.7"

services:
  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.10.0
    ports:
      - "4455:4455" # Front end hosted port
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:${KRATOS_PUBLIC_PORT:-4433}/
      - KRATOS_BROWSER_URL=http://localhost:${KRATOS_PUBLIC_PORT:-4433}/
      - PORT=4455
      - SECURITY_MODE=
    networks:
      - intranet
    restart: on-failure
