version: "3.7"
services:
  kratos-migrate:
    image: oryd/kratos:v0.10.0
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
      - SERVE_PUBLIC_BASE_URL=http://localhost:${KRATOS_PUBLIC_PORT:-4433}
      - SERVE_PUBLIC_CORS_ALLOWED_ORIGINS=${FRONT_END_HOST:-http://localhost:3000}
      - SELFSERVICE_DEFAULT_BROWSER_RETURN_URL=${FRONT_END_HOST:-http://localhost:3000}
      - SERVE_ADMIN_BASE_URL=http://kratos:${KRATOS_ADMIN_PORT:-4434}
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./config
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml ${KRATOS_STATIC_SITE- -c /etc/config/kratos/kratos-ssr.yml} migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.10.0
    ports:
      - "${KRATOS_PUBLIC_PORT:-4433}:${KRATOS_PUBLIC_PORT:-4433}" # public
      - "${KRATOS_ADMIN_PORT:-4434}:${KRATOS_ADMIN_PORT:-4434}" # admin
    restart: unless-stopped
    environment:
      - LOG_LEVEL=trace
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - SERVE_PUBLIC_BASE_URL=http://localhost:${KRATOS_PUBLIC_PORT:-4433}
      - SERVE_PUBLIC_CORS_ALLOWED_ORIGINS=${FRONT_END_HOST:-http://localhost:3000}
      - SELFSERVICE_DEFAULT_BROWSER_RETURN_URL=${FRONT_END_HOST:-http://localhost:3000}
      - SERVE_ADMIN_BASE_URL=http://kratos:${KRATOS_ADMIN_PORT:-4434}
    command: serve -c /etc/config/kratos/kratos.yml ${KRATOS_STATIC_SITE- -c /etc/config/kratos/kratos-ssr.yml} --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./config
        target: /etc/config/kratos
    networks:
      - intranet
networks:
  intranet:
volumes:
  kratos-sqlite:
